"""Excepciones"""
# Cada vez que tu código intenta hacer algo erróneo, irresponsable o inaplicable, Python hace dos cosas:

#         Detiene tu programa.
#         Crea un tipo especial de dato, llamado excepción.
# Ambas actividades llevan por nombre generar una excepción. Podemos decir que Python siempre genera una excepción (o que una excepción ha sido generada) cuando no tiene idea de qué hacer con el código.

# ¿Qué ocurre después?

#         La excepción generada espera que alguien o algo lo note y haga algo al respecto.
#         Si la excepción no es resuelta, el programa será terminado abruptamente, y verás un mensaje de error enviado a la consola por Python.
#         De otra manera, si se atiende la excepción y es manejada apropiadamente, el programa puede reanudarse y su ejecución puede continuar.
# Python proporciona herramientas efectivas que permiten observar, identificar y manejar las excepciones eficientemente. Esto es posible debido a que todas las excepciones potenciales tienen un nombre específico, por lo que se pueden clasificar y reaccionar a ellas adecuadamente.


# Ya conoces algunos nombres de las excepciones. Observa el siguiente mensaje de diagnóstico:

# ValueError: math domain error 
# salida

# La palabra resaltada es el nombre de la excepción. Vamos a familiarizarnos con algunas otras excepciones.